name: pogo
adopt-info: pogo
base: core20
summary: A fast and minimalist audio player for Linux
description: |
  Pogo is a fast and minimalist audio player for Linux. It
  groups tracks by album, which uses less space and simplifies
  rearranging your playlist. Pogo does not organize your tracks in a
  music library and does not stream or download tracks. Therefore, it is
  best suited for people who store their tracks by album and want a
  simple way of playing them. Pogo allows you to quickly search for music
  on local drives and in the playlist. It also features an equalizer and
  displays covers and desktop notifications. Pogo is a fork of Decibel
  Audio Player and supports most common audio formats. It is written in
  Python and uses GTK+ and GStreamer.
grade: stable
confinement: strict
architectures:
  - build-on: amd-64
compression: lzo

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: org.mpris.pogo

parts:
  dependencies:
    plugin: nil
    stage-packages:
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-glib-2.0
      - gir1.2-gstreamer-1.0
      - gir1.2-gtk-3.0
      - gir1.2-pango-1.0
      - gir1.2-notify-0.7
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - python3-dbus
      - python3-gi
      - python3-mutagen
      - python3-pil
      - libgl1
      - libglu1-mesa
      - freeglut3
      - libgpm2
      - libslang2

  pogo:
    after:
      - dependencies
    plugin: nil
    source: .
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "v1.0.1"
    override-build: |
      prefix=$SNAPCRAFT_PART_INSTALL make install
      sed -i 's/^prefix = .*/import os\nprefix = os.environ.get("SNAP")/g' $SNAPCRAFT_PART_INSTALL/bin/pogo
    build-packages:
      - gettext

apps:
  pogo:
    extensions:
      - gnome-3-38
    command: bin/pogo
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP_DESKTOP_RUNTIME/usr/lib/python3.6/site-packages:$PYTHONPATH
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
    plugs:
      - process-control
      - x11
    slots:
      - dbus-daemon
    plugs:
      - mpris
      - network-bind
      - unity7
      - home
      - network
      - opengl
      - audio-playback
      - removable-media
      - mount-observe
      - hardware-observe
